Fix python3 support for builder.py
subprocess.Popen().communicate() returns a byte string in Python 3 (equal to a standard string in Python 2). Attempting to decode the string works on both Python 2 and Python 3 and fixes the following error:

```
==> Generating an env.sh
Unhandled exception of type 'TypeError':
Traceback (most recent call last):
  File "./src/catkin/bin/../python/catkin/builder.py", line 981, in build_workspace_isolated
    number=index + 1, of=len(ordered_packages)
  File "./src/catkin/bin/../python/catkin/builder.py", line 691, in build_package
    destdir=destdir, use_ninja=use_ninja
  File "./src/catkin/bin/../python/catkin/builder.py", line 606, in build_cmake_package
    arch = get_multiarch()
  File "./src/catkin/bin/../python/catkin/builder.py", line 284, in get_multiarch
    assert(not out.strip() or out.strip().count('-') == 2)
TypeError: a bytes-like object is required, not 'str'
<== Failed to process package 'octomap': 
  a bytes-like object is required, not 'str'
Command failed, exiting.
```