meh.   on hudson, build complaining:
abort: http authorization required
ERROR: Failed to install tree '/home/rosbuild/hudson/workspace/catkin-wet-incremental.PLEASE.DONT.BREAK.THIS.BUILD/src/rospkg'
 Checkout of https://kforge.ros.org/rosrelease/rospkg version  into /home/rosbuild/hudson/workspace/catkin-wet-incremental.PLEASE.DONT.BREAK.THIS.BUILD/src/rospkg failed.